src/DevBetterWeb.Web/Constants.cs
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Pages/ArchivedVideos/Delete.cshtml.cs
src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml
src/DevBetterWeb.Web/Pages/ArchivedVideos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/ArchivedVideos/Index.cshtml
src/DevBetterWeb.Web/Pages/ArchivedVideos/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/_ViewImports.cshtml
src/DevBetterWeb.Web/Startup.cs

Hiding Links from Non-Admin Users for Create/Edit/Delete

---

src/DevBetterWeb.Core/Entities/ArchiveVideo.cs
src/DevBetterWeb.Core/Entities/Question.cs
src/DevBetterWeb.Infrastructure/Data/AppDbContext.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20190301183038_AddQuestions.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20190301183038_AddQuestions.cs
src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Questions.cshtml
src/DevBetterWeb.Web/Pages/Questions.cshtml.cs
src/DevBetterWeb.Web/Views/Home/Index.cshtml
src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml

Add questions feature

---

src/DevBetterWeb.Core/Entities/ArchiveVideo.cs
tests/DevBetterWeb.Tests/Core/Entities/ArchiveVideoNew.cs
tests/DevBetterWeb.Tests/DevBetterWeb.Tests.csproj

Adding a failing test

---

src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml
src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml.cs
src/DevBetterWeb.Web/Views/Shared/DisplayTemplates/ListQuestions.cshtml
tests/DevBetterWeb.Tests/Integration/Data/EfRepositoryShould.cs
tests/DevBetterWeb.Tests/Integration/Web/ApiToDoItemsControllerListShould.cs

Add Question List to Video Details Page

---

src/DevBetterWeb.Core/Interfaces/IDomainEventDispatcher.cs
src/DevBetterWeb.Infrastructure/DevBetterWeb.Infrastructure.csproj
src/DevBetterWeb.Infrastructure/DomainEvents/DomainEventDispatcher.cs
src/DevBetterWeb.Web/Areas/Identity/IdentityHostingStartup.cs
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Program.cs
src/DevBetterWeb.Web/Startup.cs
src/DevBetterWeb.Web/appsettings.json
tests/DevBetterWeb.Tests/NoOpDomainEventDispatcher.cs

Also switching to Autofac from StructureMap

Configuring things for Azure sql use

---

src/DevBetterWeb.Web/Pages/ArchivedVideos/Create.cshtml
src/DevBetterWeb.Web/Pages/ArchivedVideos/Create.cshtml.cs
src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml
src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/ArchivedVideos/Edit.cshtml
src/DevBetterWeb.Web/Pages/ArchivedVideos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/ArchivedVideos/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/Questions.cshtml
src/DevBetterWeb.Web/wwwroot/js/videos.js

restyled questions page.  did some basic work on create video page.  updated edit video page, adding create, edit, and delete question functionality

101419 question page

---

src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Views/Home/Index.cshtml
src/DevBetterWeb.Web/web.config

- Adjusting the maxAllowedContextLength to allow up to 500mb file uploads
- Adjusting line on home page to remove "bi-weekly"

Fixing issues during deployment

---

src/DevBetterWeb.Web/Views/Home/Index.cshtml

Reading through this yesterday, I felt like the collaboration we get from Discord isn't highlighted enough. It seems to be a very useful component to making devBetter what it is. The collaboration, questions, discussions, etc there are great and happen just about on a daily basis.
This is to just spark some ideas of how to word this. Definitely open to additions to this.

Updates to home page content

---

src/DevBetterWeb.Web/Areas/Identity/Pages/Account/AccessDenied.cshtml
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
src/DevBetterWeb.Web/Views/Home/Index.cshtml
src/DevBetterWeb.Web/wwwroot/css/site.css

#45 -  Add link for how to sign up on Access Denied page
- Adding custom Access Denied Identity page displayed when logged in, and not yet a member pf devBetter and attempt to view the "Videos"
- Moving inline styling for 'Join Monthly' button to site.css & increasing width of button by 1px to render correctly on Firefox.

Add link for how to sign up on Access Denied page

---

src/DevBetterWeb.Web/wwwroot/css/site.css

Removing extra character from site.css

Remove.unneccesary.character.site.css

---

src/DevBetterWeb.Web/Pages/User/Details.cshtml

added style="white-space: pre-line;" to about info card

updated about info display

---

src/DevBetterWeb.Web/Pages/Questions.cshtml
src/DevBetterWeb.Web/Pages/Questions.cshtml.cs
src/DevBetterWeb.Web/Startup.cs
tests/DevBetterWeb.Tests/Integration/Web/QuestionsPageGet.cs

Add back in Questions page
Add a test for Questions page

Cleanup and Fix Questions Page Bug

---

src/DevBetterWeb.Core/Events/UserAddedToRoleEvent.cs
src/DevBetterWeb.Core/Events/UserRemovedFromRoleEvent.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogUserAddedToRoleHandler.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogUserRemovedFromRoleHandler.cs
src/DevBetterWeb.Web/Pages/Admin/Role.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/User.cshtml.cs
tests/DevBetterWeb.Tests/Integration/Web/HomeControllerIndexShould.cs
tests/DevBetterWeb.Tests/Integration/Web/QuestionsPageGet.cs

Adding events and notifications on role changes

---

src/DevBetterWeb.Core/Exceptions/RoleNotFoundException.cs
src/DevBetterWeb.Core/Exceptions/UserNotFoundException.cs
src/DevBetterWeb.Core/Interfaces/IUserRoleMembershipService.cs
src/DevBetterWeb.Infrastructure/Services/AspNetCoreIdentityUserRoleMembershipService.cs
src/DevBetterWeb.Web/Pages/Admin/Role.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/User.cshtml.cs

Added interface
Added custom exceptions
Removed duplication from Role and User pages.

Created UserRoleMembershipService

---

src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml

added popperJs script reference to staging and production environments.  fix for #96

Update _Layout.cshtml with popperJs script reference

---

src/DevBetterWeb.Web/Views/Home/Index.cshtml
src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml
src/DevBetterWeb.Web/Views/Shared/_LoginPartial.cshtml
src/DevBetterWeb.Web/web.config
src/DevBetterWeb.Web/wwwroot/css/site.css

-removed octo cat from corner and put a link in the nav bar
-created submenu for user account actions
-added responsive bootstrap classes so it will collapse on smaller screens
-reorganized nav items
all for issue  #70 !

Nav menu updates

---

src/DevBetterWeb.Core/DevBetterWeb.Core.csproj
src/DevBetterWeb.Core/Interfaces/IRepository.cs
src/DevBetterWeb.Core/Specs/ArchiveVideoWithQuestionsSpec.cs
src/DevBetterWeb.Core/Specs/MemberByUserIdSpec.cs
src/DevBetterWeb.Infrastructure/Data/EfRepository.cs
src/DevBetterWeb.Infrastructure/DevBetterWeb.Infrastructure.csproj
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Pages/ArchivedVideos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Questions.cshtml.cs
src/DevBetterWeb.Web/Pages/User/Details.cshtml
src/DevBetterWeb.Web/Pages/User/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/User/Index.cshtml
src/DevBetterWeb.Web/Pages/User/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MyProfile.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile.cshtml.cs
src/DevBetterWeb.Web/Pages/User/UserDetailsViewModel.cs
tests/DevBetterWeb.Tests/DevBetterWeb.Tests.csproj

- icon on member list
- address for admins only on details view
- update nuget packages

Add Address Info

---

efscripts.txt
src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Infrastructure/Data/Config/MemberConfig.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20201104211836_DiscordUsername.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20201104211836_DiscordUsername.cs
src/DevBetterWeb.Web/CustomAttributes/ValidDiscordUsernameAttribute.cs
src/DevBetterWeb.Web/CustomAttributes/ValidUrlAttribute.cs
src/DevBetterWeb.Web/Pages/User/Details.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Personal.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Personal.cshtml.cs
src/DevBetterWeb.Web/Pages/User/UserDetailsViewModel.cs
src/DevBetterWeb.Web/Pages/User/UserPersonalUpdateModel.cs
src/DevBetterWeb.Web/Pages/User/UserProfileViewModel.cs
tests/DevBetterWeb.Tests/Core/Entities/MemberTests/MemberAddBook.cs
tests/DevBetterWeb.Tests/Core/Entities/ValidDiscordUsernameAttributeHelpersTests/ValidDiscordUsernameAttributeHelpersHasFourDigitNumAtEndShould.cs
tests/DevBetterWeb.Tests/Core/Entities/ValidDiscordUsernameAttributeHelpersTests/ValidDiscordUsernameAttributeHelpersHasHashtagFourFromEndShould.cs

Discord username add

---

src/DevBetterWeb.Core/Entities/Book.cs
src/DevBetterWeb.Core/Events/NewBookCreatedEvent.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogNewBookAddedToGeneralListHandler.cs
src/DevBetterWeb.Web/Pages/Admin/Books/Create.cshtml.cs
src/DevBetterWeb.Web/appsettings.json

Add New Book Added Event Handler

---

src/DevBetterWeb.Infrastructure/Handlers/DiscordLogMemberUpdateHandler.cs
src/DevBetterWeb.Infrastructure/Services/DevBetterComNotificationsWebhook.cs
src/DevBetterWeb.Infrastructure/Services/DiscordWebhookUrls.cs
src/DevBetterWeb.Web/appsettings.json

Change profile updates to go to devbettercom-notifications channel

---

src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Create.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Create.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Delete.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Delete.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Details.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Edit.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Books/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Users/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Users/Index.cshtml.cs
src/DevBetterWeb.Web/Program.cs
src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml
src/DevBetterWeb.Web/appsettings.json

As per https://github.com/DevBetterCom/DevBetterWeb/issues/162
Note that as is, this repo has been updated to my local db connection string and the SeedDb block in Program.cs. My Git powers are not strong enough to know the best way to over-ride those before merging back to the remote.

Admin landing page with Books, Users, and Videos

---

src/DevBetterWeb.Core/Events/MemberAvatarUpdatedEvent.cs
src/DevBetterWeb.Core/Events/MemberUpdatedEvent.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogMemberAvatarUpdateHandler.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogMemberUpdateHandler.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/EditAvatar.cshtml.cs

fixes #167 
I wasn't sure if I should put stuff like the repository and dispatcher into edit avatar, but that seemed like the most straightforward way to do that.

avatar update triggers devbettercom notifications webhook

---

src/DevBetterWeb.Web/Pages/User/Details.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/EditAvatar.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/User/UserDetailsViewModel.cs

Add Avatar Image to User Details Page

---

src/DevBetterWeb.Web/appsettings.json

Set DefaultConnection back to use the correct database name

---

README.md
src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Core/Events/MemberAddressUpdatedEvent.cs
src/DevBetterWeb.Core/ValueObjects/Address.cs
src/DevBetterWeb.Core/ValueObjects/Geolocation.cs
src/DevBetterWeb.Infrastructure/Data/Config/MemberConfig.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20210207162757_AddShippingAddress.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20210207162757_AddShippingAddress.cs
src/DevBetterWeb.Infrastructure/Services/LoggerEmailServiceDecorator.cs
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Pages/User/Map.cshtml.cs
src/DevBetterWeb.Web/migrate.sql
tests/DevBetterWeb.Tests/Core/Entities/MemberTests/MemberUpdateLinks.cs

Updating member to include handler to update Geolocation when Address changes.

Adding migrations and support for Address and Geolocation value objects

---

src/DevBetterWeb.Web/Pages/Admin/Users/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Users/Index.cshtml.cs

I couldn't make it work with the buttons, so it's not as pretty as it was, but the users page should now filter correctly
fixes #193

admin user page fix

---

src/DevBetterWeb.Core/Interfaces/IAppLogger.cs
src/DevBetterWeb.Infrastructure/Logging/LoggerAdapter.cs

Created IAppLogger and LoggerAdapter 

---

src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Links.cshtml.cs
src/DevBetterWeb.Web/Pages/User/UserProfileViewModel.cs

null object pattern implemented on MyProfile page

---

src/DevBetterWeb.Core/Interfaces/IMemberSubscriptionPeriodCalculationsService.cs
src/DevBetterWeb.Core/Services/MemberSubscriptionPeriodCalculationsService.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml.cs

fixes #178 
May conflict with a previous PR of mine. Please merge this after #216 and #217. If there are conflicts I will resubmit.

alumni progress bar implemented

---

src/DevBetterWeb.Web/CustomAttributes/ValidDiscordUsernameAttribute.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Personal.cshtml

discord username doesn't blow up

---

src/DevBetterWeb.Core/Interfaces/IMemberSubscriptionPeriodCalculationsService.cs
src/DevBetterWeb.Core/Services/MemberSubscriptionPeriodCalculationsService.cs
src/DevBetterWeb.Web/Pages/User/Details.cshtml
src/DevBetterWeb.Web/Pages/User/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/User/Index.cshtml
src/DevBetterWeb.Web/Pages/User/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MemberSubscriptionPercentViewModel.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/User/_MemberSubscriptionPercentBar.cshtml
src/DevBetterWeb.Web/Pages/User/_MemberSubscriptionPercentCircle.cshtml

fixes #208 
Also adds alumni progress bar from MyProfile to member details

Subscription percent circle

---

src/DevBetterWeb.Core/Specs/BillingActivitiesByDateTimeRangeAndCancelledVerbSpec.cs
src/DevBetterWeb.Core/Specs/BillingActivitiesByDateTimeRangeAndSubscribedVerbSpec.cs
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Pages/Admin/UserReports/Cancellations.cshtml
src/DevBetterWeb.Web/Pages/Admin/UserReports/Cancellations.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/UserReports/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/UserReports/ReportsDatesModel.cs
src/DevBetterWeb.Web/Pages/Admin/UserReports/Signups.cshtml.cs
src/DevBetterWeb.Web/Pages/User/UserBillingViewModel.cs

fixes #180 
Yes, there should be a partial for the various admin report pages, but I couldn't get that to work with the data binding for the dates, so I decided the small amount of tech debt from duplicating those pages was an acceptable trade-off to hitting my head against the wall trying to get the partial to work.

Cancellations report

---

README.md
src/DevBetterWeb.Core/Events/UserEmailConfirmedChangedEvent.cs
src/DevBetterWeb.Core/Interfaces/IUserEmailConfirmationService.cs
src/DevBetterWeb.Infrastructure/DefaultInfrastructureModule.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogUserEmailConfirmedChangedHandler.cs
src/DevBetterWeb.Infrastructure/Services/AspNetCoreIdentityUserEmailConfirmationService.cs
src/DevBetterWeb.Web/Pages/Admin/User.cshtml
src/DevBetterWeb.Web/Pages/Admin/User.cshtml.cs

Added change email confirmation by admin and discord log for that

---

src/DevBetterWeb.Core/DevBetterWeb.Core.csproj
src/DevBetterWeb.Infrastructure/DevBetterWeb.Infrastructure.csproj
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Pages/Admin/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Members/Cancel.cshtml
src/DevBetterWeb.Web/Pages/Admin/Members/Cancel.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Members/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Members/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/Checkout/Success.cshtml
tests/DevBetterWeb.Tests/DevBetterWeb.Tests.csproj

Moved ranking to service. Added tests. Maybe service needs an orderby parameter - right now it defaults to descending order for rank.

Rank Fixing #313

---

src/DevBetterWeb.Core/Interfaces/IAppLogger.cs
src/DevBetterWeb.Infrastructure/DiscordWebhooks/AdminUpdatesWebhook.cs
src/DevBetterWeb.Infrastructure/DiscordWebhooks/BaseWebhook.cs
src/DevBetterWeb.Infrastructure/DiscordWebhooks/BookDiscussionWebhook.cs
src/DevBetterWeb.Infrastructure/DiscordWebhooks/DevBetterComNotificationsWebhook.cs
src/DevBetterWeb.Infrastructure/Logging/LoggerAdapter.cs
src/DevBetterWeb.Web/Pages/User/Index.cshtml

Fixing errors locally with webhooks and invalid URLs
Fixes #279

Fixing sorting of progress circles

---

src/DevBetterWeb.Web/Pages/Resources/Index.cshtml
src/DevBetterWeb.Web/Pages/Resources/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/User/Index.cshtml
src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml

Initial resources page

---

README.md
src/DevBetterWeb.Core/Entities/Invitation.cs
tests/DevBetterWeb.Tests/Services/DailyCheckPingServiceTests/CheckIfAnyActiveInvitationsRequireAdminPing.cs
tests/DevBetterWeb.Tests/Services/DailyCheckPingServiceTests/CheckIfAnyActiveInvitationsRequireUserPing.cs
tests/DevBetterWeb.Tests/Services/DailyCheckPingServiceTests/InvitationBuilder.cs
tests/DevBetterWeb.Tests/Services/DailyCheckPingServiceTests/ReflectionHelperExtensionMethods.cs

refactored to use reflection and builder pattern

tests of daily check ping service 

---

src/DevBetterWeb.Core/Entities/MemberSubscriptionPlan.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Billing.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Billing.cshtml.cs

fixes #177 
Left the sorting from earliest to latest going down, since using table.sm makes it so even if it's a lot of data it should all fit on one screen

Billing page format fixed

---

src/DevBetterWeb.Infrastructure/Data/AppDbContext.cs
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
src/DevBetterWeb.Web/Pages/Admin/Books/Create.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Create.cshtml
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Create.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Delete.cshtml
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Delete.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Details.cshtml
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Edit.cshtml
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/Resources/Index.cshtml.cs

CRUD available to admins for MemberSubscriptionPlan

Member subscription plan addition

---

src/DevBetterWeb.Core/Interfaces/IDailyCheckPingService.cs
src/DevBetterWeb.Infrastructure/Handlers/DailyCheckInitiatedEventHandler.cs
src/DevBetterWeb.Infrastructure/Services/DailyCheckPingService.cs
tests/DevBetterWeb.Tests/Services/DailyCheckPingServiceTests/CheckIfAnyActiveInvitationsRequireAdminPing.cs
tests/DevBetterWeb.Tests/Services/DailyCheckPingServiceTests/CheckIfAnyActiveInvitationsRequireUserPing.cs

daily check added to remind admins to make sure upcoming alumni do not have subscription renewed
eventually this should be replaced with an automatic call to stripe to cancel the subscription in question

daily check for upcoming graduation

---

src/DevBetterWeb.Web/Pages/Admin/UserReports/Cancellations.cshtml
src/DevBetterWeb.Web/Pages/Admin/UserReports/Signups.cshtml
src/DevBetterWeb.Web/Pages/Checkout/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/Checkout/Monthly.cshtml.cs
src/DevBetterWeb.Web/Pages/Checkout/Success.cshtml.cs
src/DevBetterWeb.Web/Pages/Checkout/Yearly.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Billing.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Billing.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Cancel.cshtml.cs
src/DevBetterWeb.Web/Pages/User/MyProfile/Index.cshtml
src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml

don't merge until we're ready to launch stripe

Final PR for Stripe payment handler to go live

---

src/DevBetterWeb.Core/Entities/ArchiveVideo.cs
src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Core/Entities/MemberVideo.cs
src/DevBetterWeb.Core/Entities/MemberVideoProgress.cs
src/DevBetterWeb.Core/Interfaces/IMarkdownService.cs
src/DevBetterWeb.Core/Specs/ArchiveVideoByPageSpec.cs
src/DevBetterWeb.Core/Specs/ArchiveVideoByVideoIdSpec.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20210914184658_MIGRATIONNAME.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20210914184658_MIGRATIONNAME.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20210916044929_VideoProgress.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20210916044929_VideoProgress.cs
src/DevBetterWeb.Infrastructure/Services/MarkdigService.cs
src/DevBetterWeb.UploaderApp/AddVideoInfo.cs
src/DevBetterWeb.UploaderApp/ArchiveVideo.cs
src/DevBetterWeb.UploaderApp/DevBetterWeb.UploaderApp.csproj
src/DevBetterWeb.UploaderApp/Program.cs
src/DevBetterWeb.UploaderApp/UploaderManager.cs
src/DevBetterWeb.Vimeo/Models/Video.cs
src/DevBetterWeb.Vimeo/Services/VideoServices/GetAllVideosService.cs
src/DevBetterWeb.Web/Controllers/VideosController.cs
src/DevBetterWeb.Web/MappingProfiles/VideoProfile.cs
src/DevBetterWeb.Web/Models/ArchiveVideoDto.cs
src/DevBetterWeb.Web/Pages/Videos/Delete.cshtml.cs
src/DevBetterWeb.Web/Pages/Videos/DeleteAll.cshtml
src/DevBetterWeb.Web/Pages/Videos/DeleteAll.cshtml.cs
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Videos/Edit.cshtml
src/DevBetterWeb.Web/Pages/Videos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Videos/Index.cshtml
src/DevBetterWeb.Web/wwwroot/js/videos.js

- Archive video used.
- Uploader read the encoded date from the file.

Archive video applied

---

src/DevBetterWeb.Web/Views/Shared/_Layout.cshtml

Add FAQ link to public navigation

Add FAQ link to public navigation

---

src/DevBetterWeb.Web/Controllers/VideosController.cs
src/DevBetterWeb.Web/Models/UpdateDescription.cs
src/DevBetterWeb.Web/Pages/Admin/Videos/OEmbedViewModel.cs
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml.cs

Shady nagy/video description edit

---

.github/workflows/ci-cd.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dotnetcore.yml
.github/workflows/publish.yml
src/DevBetterWeb.Core/DevBetterWeb.Core.csproj
src/DevBetterWeb.Infrastructure/DevBetterWeb.Infrastructure.csproj
src/DevBetterWeb.UploaderApp/DevBetterWeb.UploaderApp.csproj
src/DevBetterWeb.Web/DevBetterWeb.Web.csproj
tests/DevBetterWeb.FunctionalTests/DevBetterWeb.FunctionalTests.csproj
tests/DevBetterWeb.Tests/DevBetterWeb.Tests.csproj
tests/DevBetterWeb.UnitTests/DevBetterWeb.UnitTests.csproj
tests/DevBetterWeb.Vimeo.Tests/DevBetterWeb.Vimeo.Tests.csproj

- updates minor/patch versions of most packages 
- does not update `SixLabors.ImageSharp` since I wasn't completely aware of side effects from this
- update codeql-analysis.yml to use v2 actions

Update packages and GitHub actions

---

src/DevBetterWeb.Core/Entities/ArchiveVideo.cs
src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Core/Entities/MemberVideoProgress.cs
src/DevBetterWeb.Core/Specs/ArchiveVideoByPageSpec.cs
src/DevBetterWeb.Core/Specs/MemberByUserIdWithFavoriteArchiveVideosSpec.cs
src/DevBetterWeb.Core/ValueObjects/MemberFavoriteArchiveVideo.cs
src/DevBetterWeb.Infrastructure/Data/Config/ArchiveVideoConfig.cs
src/DevBetterWeb.Infrastructure/Data/Config/MemberConfig.cs
src/DevBetterWeb.Infrastructure/Data/Config/MemberFavoriteVideoConfig.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220523231128_AddMemberFavoriteVideo.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220523231128_AddMemberFavoriteVideo.cs
src/DevBetterWeb.Web/ConfigureServicesExtensions.cs
src/DevBetterWeb.Web/Controllers/VideosController.cs
src/DevBetterWeb.Web/Models/ArchiveVideoDto.cs
src/DevBetterWeb.Web/Models/DataTableParameterModel.cs
src/DevBetterWeb.Web/Pages/Admin/Videos/OEmbedViewModel.cs
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Videos/Index.cshtml
src/DevBetterWeb.Web/SeedData.cs
src/DevBetterWeb.Web/Startup.cs
src/DevBetterWeb.Web/migrate.sql
tests/DevBetterWeb.UnitTests/Core/Entities/MemberTests/MemberAddFavoriteArchiveVideo.cs
tests/DevBetterWeb.UnitTests/Core/Entities/MemberTests/MemberRemoveFavoriteArchiveVideo.cs
tests/DevBetterWeb.UnitTests/Core/Specs/ArchiveVideoByPageSpecEvaluate.cs
tests/DevBetterWeb.UnitTests/Core/ValueObjects/MemberFavoriteArchiveVideoConstructor.cs

- adds ability to toggle videos as favorites 
- filter video list by favorites
- adds `MemberFavoriteArchiveVideo` value object
fixes #684

Mark Videos As Favorites

---

src/DevBetterWeb.UploaderApp/DevBetterWeb.UploaderApp.csproj
src/DevBetterWeb.UploaderApp/UploaderService.cs
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/EmailVerificationRequired.cshtml.cs
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/Login.cshtml.cs
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
src/DevBetterWeb.Web/Controllers/VideosController.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Books/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/SubscriptionPlans/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Videos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/Questions.cshtml.cs
src/DevBetterWeb.Web/Pages/User/Map.cshtml.cs
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml.cs
src/DevBetterWeb.Web/SeedData.cs
tests/DevBetterWeb.Tests/Integration/Web/CustomWebApplicationFactory.cs
tests/DevBetterWeb.Tests/Services/NewMemberServiceTests/CreateInvitation.cs
tests/DevBetterWeb.Tests/Services/NewMemberServiceTests/SendRegistrationEmail.cs
tests/DevBetterWeb.Tests/Services/NewMemberServiceTests/VerifyValidEmailAndInviteCode.cs
tests/DevBetterWeb.UnitTests/Core/Events/BillingActivityCreatedEventConstructor.cs
tests/DevBetterWeb.UnitTests/Core/Events/SubscriptionAddedEventConstructor.cs
tests/DevBetterWeb.UnitTests/Core/Events/SubscriptionUpdatedEventConstructor.cs
tests/DevBetterWeb.UnitTests/DevBetterWeb.UnitTests.csproj

This PR cleans up most of the warnings in the solution.  There are still some that I wasn't sure what to do with in the DevBetterWeb.Uploader app project because I believe that one is still a work in progress.  The warnings in all other projects have been cleaned up.
This PR will close #749 and #210.

Resolve Null Related Warnings

---

src/DevBetterWeb.Core/Specs/ArchiveVideoByVideoIdWithMemberFavoritesSpec.cs
src/DevBetterWeb.Web/Pages/Videos/Details.cshtml.cs
src/DevBetterWeb.Web/SeedData.cs

- fixes issue where list and detail views could display a difference of 1 in the favorites count

Fix favorites count issue

---

src/DevBetterWeb.Core/Specs/MembersByUsersIdSpec.cs
src/DevBetterWeb.Web/Models/MemberLinksDTO.cs
src/DevBetterWeb.Web/Pages/User/Index.cshtml
src/DevBetterWeb.Web/Pages/User/Index.cshtml.cs
tests/DevBetterWeb.Tests/Integration/Web/MemberLinksDtoFromMemberEntity.cs

Shady nagy/recent inactive members

---

src/DevBetterWeb.Web/Pages/User/MyProfile/Links.cshtml
src/DevBetterWeb.Web/Pages/User/MyProfile/Personal.cshtml

Profile personal and linkes pages tooltip added.

---

src/DevBetterWeb.Core/Entities/ArchiveVideo.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220712095137_SHOW_NOTES_REMOVED.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220712095137_SHOW_NOTES_REMOVED.cs
src/DevBetterWeb.Web/Controllers/VideosController.cs
src/DevBetterWeb.Web/Models/ArchiveVideoDto.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Create.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Create.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Details.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Details.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Edit.cshtml
src/DevBetterWeb.Web/Pages/Admin/ArchivedVideos/Edit.cshtml.cs
src/DevBetterWeb.Web/Pages/DisplayConstants.cs

Shady nagy/remove show notes

---

src/DevBetterWeb.Web/Pages/User/Index.cshtml
src/DevBetterWeb.Web/wwwroot/js/members.js

- No need for DB changes.
Fix #785

All members checkbox.

---

src/DevBetterWeb.Core/Interfaces/INewMemberService.cs
src/DevBetterWeb.Core/Services/NewMemberService.cs
src/DevBetterWeb.Web/MappingProfiles/InvitationProfile.cs
src/DevBetterWeb.Web/Models/InvitationDto.cs
src/DevBetterWeb.Web/Pages/Admin/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Invitations/Deactivate.cshtml
src/DevBetterWeb.Web/Pages/Admin/Invitations/Deactivate.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Invitations/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Invitations/Index.cshtml.cs
src/DevBetterWeb.Web/wwwroot/js/admin.js

Invitations added.

---

src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Core/Events/MemberHomeAddressUpdatedEvent.cs
src/DevBetterWeb.Infrastructure/Handlers/DiscordLogMemberUpdateHomeAddressHandler.cs
src/DevBetterWeb.Infrastructure/Handlers/MemberAddressUpdatedHandler.cs

Send discord message omn admin channel when address changed.

---

src/DevBetterWeb.Web/wwwroot/js/site.js

fix the error image.

---

src/DevBetterWeb.Infrastructure/DefaultInfrastructureModule.cs

- No DB changes are needed
Fix #578

Discord_Video_Add Activated.

---

src/DevBetterWeb.Core/Entities/Book.cs
src/DevBetterWeb.Core/Entities/BookCategory.cs
src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Core/Entities/VideoComment.cs
src/DevBetterWeb.Core/Specs/BookByIdWithMembersSpec.cs
src/DevBetterWeb.Core/Specs/BookCategoriesSpec.cs
src/DevBetterWeb.Core/Specs/BooksByMemberReadCountWithMembersWhoHaveReadSpec.cs
src/DevBetterWeb.Core/Specs/MemberByUserIdWithBooksReadAndMemberSubscriptionsSpec.cs
src/DevBetterWeb.Core/Specs/MemberByUserIdWithBooksReadSpec.cs
src/DevBetterWeb.Core/Specs/MembersHavingUserIdsWithBooksSpec.cs
src/DevBetterWeb.Infrastructure/Data/AppDbContext.cs
src/DevBetterWeb.Infrastructure/Data/Config/BookCategoryConfig.cs
src/DevBetterWeb.Infrastructure/Data/Config/BookConfig.cs
src/DevBetterWeb.Infrastructure/Data/Config/MemberConfig.cs
src/DevBetterWeb.Infrastructure/Data/Config/VideoCommentConfig.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220714020556_Book_Category.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220714020556_Book_Category.cs
src/DevBetterWeb.Web/MappingProfiles/BookCategoryProfile.cs
src/DevBetterWeb.Web/MappingProfiles/BookProfile.cs
src/DevBetterWeb.Web/MappingProfiles/MemberProfile.cs
src/DevBetterWeb.Web/Models/BookCategoryDto.cs
src/DevBetterWeb.Web/Models/BookDto.cs
src/DevBetterWeb.Web/Models/MemberForBookDto.cs
src/DevBetterWeb.Web/Pages/Leaderboard/Index.cshtml
src/DevBetterWeb.Web/Pages/Leaderboard/Index.cshtml.cs
src/DevBetterWeb.Web/Program.cs
src/DevBetterWeb.Web/SeedData.cs

- `Need` DB changes 1st before deploying/Merging as it will add the book category in the 1st run.
Fix #336

Shady nagy/book categories

---

src/DevBetterWeb.Infrastructure/Data/Migrations/20220714170447_DateCreated.Designer.cs
src/DevBetterWeb.Infrastructure/Data/Migrations/20220714170447_DateCreated.cs
src/DevBetterWeb.Infrastructure/Identity/Data/AppIdentityDbContextSeed.cs
src/DevBetterWeb.Infrastructure/Identity/Data/ApplicationUser.cs
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/NewMemberRegister.cshtml.cs
src/DevBetterWeb.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
src/DevBetterWeb.Web/Pages/Admin/Users/Index.cshtml
src/DevBetterWeb.Web/Pages/Admin/Users/Index.cshtml.cs

- `Need` DB changes identity only
Fix #144

Shady nagy/add date created admin

---

src/DevBetterWeb.Core/Entities/BookCategory.cs
src/DevBetterWeb.Core/Entities/Member.cs
src/DevBetterWeb.Web/MappingProfiles/MemberProfile.cs
src/DevBetterWeb.Web/Pages/Leaderboard/Index.cshtml
src/DevBetterWeb.Web/Pages/Leaderboard/Index.cshtml.cs

Apply order by rank for members.

---

src/DevBetterWeb.Core/Interfaces/IMemberSubscriptionEndedAdminEmailService.cs
src/DevBetterWeb.Infrastructure/Services/MemberSubscriptionEndedAdminEmailService.cs
src/DevBetterWeb.Infrastructure/Services/WebhookHandlerService.cs
tests/DevBetterWeb.Tests/Services/MemberSubscriptionEndedAdminEmailServiceTests/SendMemberSubscriptionEndedEmailAsync.cs

Shady nagy/admin email reminder cancelations

---

src/DevBetterWeb.Infrastructure/DefaultInfrastructureModule.cs
src/DevBetterWeb.Infrastructure/Interfaces/IInvoiceHandlerListService.cs
src/DevBetterWeb.Infrastructure/InvoiceHandler/StripeInvoiceHandler/StripeInvoiceHandlerListService.cs
src/DevBetterWeb.Infrastructure/IssuingHandler/StripeIssuingHandler/StripeIssuingHandlerCardListService.cs
src/DevBetterWeb.Web/ConfigureServicesExtensions.cs
src/DevBetterWeb.Web/MappingProfiles/InvoiceProfile.cs
src/DevBetterWeb.Web/Models/StripeInvoiceDto.cs
src/DevBetterWeb.Web/Pages/Admin/User.cshtml
src/DevBetterWeb.Web/Pages/Admin/User.cshtml.cs

Shady nagy/903 stripe error user admin

---

src/DevBetterWeb.Core/Specs/BooksOrderedByReadsSpec.cs
src/DevBetterWeb.Web/Interfaces/IBookService.cs
src/DevBetterWeb.Web/Pages/Books/BookViewModel.cs
src/DevBetterWeb.Web/Pages/Books/Index.cshtml
src/DevBetterWeb.Web/Pages/Books/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/_MemberLayout.cshtml
src/DevBetterWeb.Web/Services/BookService.cs
src/DevBetterWeb.Web/Views/Shared/_LoginPartial.cshtml
tests/DevBetterWeb.UnitTests/Web/Services/BookServiceTests/GetAllBooksAsync.cs

we have introduced significant improvements to the Books section of our application.
- We have introduced a new method `GetAllBooksAsync` in the `BookService` class, which fetches all books from the repository and returns them in a particular order based on their category and reads count.
- Created a new Books page.
- Unit tests have been added to ensure the correct functionality of the new method. These tests check the correct retrieval of all books, the return of an empty list when no books are present, the correct ordering of books, and the appropriate handling of exceptions when the repository fails.
We have added extensive unit tests to verify the new implementations:
1. **GetsAllBooks**
- This test verifies that the `GetAllBooksAsync` method correctly retrieves all books from the …

843 book page is created.

---

src/DevBetterWeb.Web/Pages/Calendar/Index.cshtml
src/DevBetterWeb.Web/Pages/Calendar/Index.cshtml.cs
src/DevBetterWeb.Web/Pages/_MemberLayout.cshtml

Adding Embedded Meeting Calendar to the Member Portal

---

src/DevBetterWeb.Web/Areas/Identity/Pages/Account/NewMemberRegister.cshtml.cs

/User/MyProfile redirect is fixed.

---

.github/workflows/ci-cd.yml

download-artifact downgraded to v3

---

Directory.Packages.props

- ApiClient is updated to V2.1.2
- Vimeo is updated to V2.1.2

Vimeo updated to V2.1.2

---

.github/workflows/codeql-analysis.yml

Added step to install .NET 9 in CodeQL workflow.
Resolves #1379

Install .NET 9 in CodeQL analysis workflow
